### ISSUE TITLE
Add groupchat support

### ISSUE THREAD

**Issue by e0ff** [pranomostro/ratox#13] opened 2016-10-06 04:23 UTC

**Comment by iphydf** [comment] 2016-10-09 12:49
Note that in toktok/toxcore, group chats are called "conversation" and follow the rest of the API conventions, i.e. use error enum pointers and namespaced names (e.g. `tox_del_groupchat` is now `tox_conversation_delete`).

**Comment by aaannndddyyy** [comment] 2016-10-09 18:36
Why such an unintuitive name?  Why not something that conveys the idea that it is normally not just 1:1, but a group? 
Group, group chat, and conference come to my mind

**Comment by iphydf** [comment] 2016-10-10 09:43
Sorry, I was actually wrong. It's `conference`.

**Comment by aaannndddyyy** [comment] 2016-10-10 11:31
Ah, ok. Conference is fine. So this was just a typo, I guess.
Is that rename in order to make a later transition to new group chats easier, or will old and new exists side by side, or is it general, that old and new will be called conference?
Sorry, just curious.

**Comment by iphydf** [comment] 2016-10-10 18:56
New group chats will be called "group". We chose these names, because old group chats are not persistent (i.e. when you leave, the conference is over until you are invited again), and require you to be friends with the inviter, so they are better suited for something like "conferences". Groups are more like IRC channels or other types of groups where you can join and leave at will and you don't need to know anyone in it.

**Comment by aaannndddyyy** [comment] 2016-10-11 16:09
sounds reasonable. so old ones, now called conferences, will not go away, after new groups arrive?

**Comment by iphydf** [comment] 2016-10-11 19:28
Indeed. The reason is that new group chats are currently a regression wrt. old group chats, in that they don't support TCP. I have a new-group-chats branch that I am keeping up to date with master, and I want it to be as close to master as possible, so I want it to support both group chat implementations. Clients could also implement both APIs and perhaps we'll eventually have both in master until new group chats are proven in use as reliable and feature-complete.

**Comment by pranomostro** [comment] 2016-10-22 20:44
Groupchat support is on the TODO-list. However, I first think that making file transfer and audio chat perfect and reliable before I add this.

**Comment by z3bra** [comment] 2016-11-22 14:47
Here we are then :)

**Comment by pranomostro** [comment] 2017-03-04 00:40
Just merged rudimentary conferences (supporting text-chat, leaving, joining, inviting and changing the title).

Audio comes when the API seems stable enough.

**Closed as completed by pranomostro** 2017-03-04 00:40 UTC

**Comment by aaannndddyyy** [comment] 2017-03-04 08:02
Thanks. :)
